// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rule-srv/rule-srv.proto

package go_micro_service_rulesrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RuleSrv service

func NewRuleSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RuleSrv service

type RuleSrvService interface {
	Event(ctx context.Context, in *EventRequest, opts ...client.CallOption) (*EventResponse, error)
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (RuleSrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (RuleSrv_PingPongService, error)
}

type ruleSrvService struct {
	c    client.Client
	name string
}

func NewRuleSrvService(name string, c client.Client) RuleSrvService {
	return &ruleSrvService{
		c:    c,
		name: name,
	}
}

func (c *ruleSrvService) Event(ctx context.Context, in *EventRequest, opts ...client.CallOption) (*EventResponse, error) {
	req := c.c.NewRequest(c.name, "RuleSrv.Event", in)
	out := new(EventResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "RuleSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (RuleSrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "RuleSrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &ruleSrvServiceStream{stream}, nil
}

type RuleSrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type ruleSrvServiceStream struct {
	stream client.Stream
}

func (x *ruleSrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *ruleSrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ruleSrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ruleSrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ruleSrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ruleSrvService) PingPong(ctx context.Context, opts ...client.CallOption) (RuleSrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "RuleSrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &ruleSrvServicePingPong{stream}, nil
}

type RuleSrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type ruleSrvServicePingPong struct {
	stream client.Stream
}

func (x *ruleSrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *ruleSrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *ruleSrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ruleSrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ruleSrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *ruleSrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RuleSrv service

type RuleSrvHandler interface {
	Event(context.Context, *EventRequest, *EventResponse) error
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, RuleSrv_StreamStream) error
	PingPong(context.Context, RuleSrv_PingPongStream) error
}

func RegisterRuleSrvHandler(s server.Server, hdlr RuleSrvHandler, opts ...server.HandlerOption) error {
	type ruleSrv interface {
		Event(ctx context.Context, in *EventRequest, out *EventResponse) error
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type RuleSrv struct {
		ruleSrv
	}
	h := &ruleSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&RuleSrv{h}, opts...))
}

type ruleSrvHandler struct {
	RuleSrvHandler
}

func (h *ruleSrvHandler) Event(ctx context.Context, in *EventRequest, out *EventResponse) error {
	return h.RuleSrvHandler.Event(ctx, in, out)
}

func (h *ruleSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.RuleSrvHandler.Call(ctx, in, out)
}

func (h *ruleSrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.RuleSrvHandler.Stream(ctx, m, &ruleSrvStreamStream{stream})
}

type RuleSrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type ruleSrvStreamStream struct {
	stream server.Stream
}

func (x *ruleSrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *ruleSrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ruleSrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ruleSrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ruleSrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *ruleSrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.RuleSrvHandler.PingPong(ctx, &ruleSrvPingPongStream{stream})
}

type RuleSrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type ruleSrvPingPongStream struct {
	stream server.Stream
}

func (x *ruleSrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *ruleSrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ruleSrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ruleSrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ruleSrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *ruleSrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
